// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

public enum FirstEnum
{
	e1,
	e2,
	e3,
}

// -------------------
// Customized structs
// -------------------

public struct FirstStruct
{
	public int s1;
	public float s2;
}
